title: "君のレポジトリを領域展開 - 次世代バージョン管理システム Jujutsu の紹介"
summary: "今、バージョン管理システムといえば Git です。しかしながら、Linux Kernel のコミッターの負担を軽くすることに最適化されたために、スナップショットとしての確実性・ツール規模・ユーザインタフェイスなど必ずしも完璧とはいえません。Google開発者 martinvonz 氏による新バージョン管理システム Jujutsu は Git との互換性を維持しつつ、そんな問題へ対応したツールです。本書では Jujutsu のメリットや、必要最小限のサイクルをまわせるようになるまでの簡単なオペレーションを解説します"
topics: ["jj","jujutsu","git","DVCS","VCS"]
published: false
price: 0 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - 01_abstruct
  - 02_intro
  - 03_install
  - 04_init
  - 05_work
  - 06_split
  - 07_git
  - 08_misc
  - 09_notsupport
  - 10_end
