title: "/bin/shに慣れた人に贈るバッチファイルの書き方"
summary: |-
  今日、Windowsでもバッチファイルが過去の遺物である事は間違いないですが…

  ●どこでも必ず使えるスクリプトはバッチファイル・VBScript・JScript・PowerShell しかない
  ●VBScript、JScript 、PowerShell はコマンドプロンプトからではインタプリタ名の指定を必要とする
  ●さらに PowerShell ではスクリプトの実行許可設定が必要になり、それがないとセキュリティーエラーになる

  など「どの環境でも間違いなく、そして手軽に動く」という要件を求めると、バッチファイルかバイナリの実行ファイルにせざるを得ないケースがまだ多いです。幸い、OSがNT系列になってからバッチファイルもかなり高機能になりました。なんとか頑張れば /bin/sh ほどではありませんが、必要なことができそうです。

  本書では、これまで自分が学んできたバッチファイル実装のノウハウをニーズからの逆引き形式でご紹介したいと思います。基本的にはOS標準コマンド以外のものは使わないという前提です。
topics: ["windows", "bat", "batch", "batchfile", "cmd"]
published: true
price: 0